name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t invetory:v1.23 .

      - name: List Docker Images
        run: docker images

      - name: Save Docker Image as a tar file
        run: |
          docker save myapp:v1.23 -o myapp-v1.23.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: myapp-v1.23.tar
