# This workflow will build a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go Binary and upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Create binaries directory
        run: mkdir -p binaries

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o binaries/myapp-linux app.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o binaries/myapp.exe app.go

        run: go test -v ./...

      - name: List Binaries
        run: ls -l binaries/

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: go-binaries
          path: binaries/
