# This workflow will build a Golang project

name: Build Go Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Create binaries directory
        run: mkdir -p binaries

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o binaries/myapp-linux app.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o binaries/myapp.exe app.go

      - name: List Binaries
        run: ls -l binaries/
